version: '3.8'

services:
  app:
    image: laravelphp/php-fpm
    container_name: eprocurement_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3308"
      - "DB_DATABASE=vhiweb"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=rian123123"

  web:
    image: nginx:alpine
    container_name: eprocurement_web
    ports:
      - "2025:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rian123123    
      MYSQL_DATABASE: vhiweb       
    ports:
      - "3308:3306"
    networks:
      - app-network


  redis:
    image: redis:alpine
    container_name: eprocurement_redis
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
